sudo: false
cache: bundler
language: ruby
bundler_args: --without kitchen_vagrant
rvm:
  - 2.2.2
matrix:
  include:
    - rvm: 2.2.2
      gemfile: Gemfile
script:
  - bundle exec rubocop
  - bundle exec foodcritic --exclude spec ./
#  - bundle exec rspec
